require 'hoe'
require './lib/mono/version.rb'

Hoe.spec 'monos' do

  self.version = Mono::Module::Tool::VERSION

  self.summary = "monos - monorepo / mono source tree tools and (startup) scripts"
  self.description = summary

  self.urls = { home: 'https://github.com/rubycoco/git' }

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['gitti',         '>= 0.6.1' ],
    ['gitti-backup',  '>= 0.4.1' ],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }
end
